# Head

In [1]:
from pathlib import Path

project_dir = Path("/home/zqlyu2/projects/TLDR")
data_dir = project_dir / "data"

In [2]:
import pandas as pd

with open(data_dir / "paper_html_10.1038" / "abs_annotation" / "abs_annotation.tsv", "r") as f:
    dataset_df = pd.read_csv(f, sep="\t")
dataset_df

,abs_doi,paper_id,abstract,annotation_doi,annotation
0,10.1073/pnas.91.7.2757,107202074,The origin and taxonomic status of domesticate...,10.1038/35052563,A demonstration that cattle have been domestic...
1,10.1093/genetics/154.4.1785,83366887,Abstract The domestic pig originates from the ...,10.1038/35052563,Evidence is presented for independent domestic...
2,10.1073/pnas.96.16.9252,122095374,We previously mapped a quantitative trait locu...,10.1038/35052563,This paper shows how the identity-by-descent a...
3,10.1101/gr.10.2.220,100831446,A genome-wide linkage disequilibrium (LD) map ...,10.1038/35052563,The pattern of linkage disequilibrium (LD) acr...
4,10.1126/science.8134840,17452622,The European wild boar was crossed with the do...,10.1038/35052563,The first paper to show the use of divergent i...
...,...,...,...,...,...
35636,10.2337/db08-1168,4860455,OBJECTIVE—Regulatory T-cells (Tregs) have cata...,10.1038/s41573-019-0041-4,This article describes the good manufacturing ...
35637,10.1126/science.aar3246,4860145,Engineering cytokine-receptor pairs Interleuki...,10.1038/s41573-019-0041-4,This study reports the generation of an orthog...
35638,10.1126/science.aad2791,62290395,T cells target peptide combos One of the endur...,10.1038/s41573-019-0041-4,This article shows that some diabetogenic T ce...
35639,10.1073/pnas.1902566116,82979762,Polymorphic HLAs form the primary immune barri...,10.1038/s41573-019-0041-4,This article describes the development of gene...
35640,10.4049/jimmunol.167.3.1245,20436631,Abstract Thymectomy in mice on neonatal day 3 ...,10.1038/s41573-019-0041-4,"Together with Levings et al. (2001), Jonuleit ..."

In [3]:
dataset_df.rename(columns={"abs_doi": "source_doi", 
                           "paper_id": "source_mag_paper_id",
                           "abstract": "source_abstract", 
                           "annotation_doi": "target_doi",
                           "annotation": "target_summary"}, inplace=True)
dataset_df

,source_doi,source_mag_paper_id,source_abstract,target_doi,target_summary
0,10.1073/pnas.91.7.2757,107202074,The origin and taxonomic status of domesticate...,10.1038/35052563,A demonstration that cattle have been domestic...
1,10.1093/genetics/154.4.1785,83366887,Abstract The domestic pig originates from the ...,10.1038/35052563,Evidence is presented for independent domestic...
2,10.1073/pnas.96.16.9252,122095374,We previously mapped a quantitative trait locu...,10.1038/35052563,This paper shows how the identity-by-descent a...
3,10.1101/gr.10.2.220,100831446,A genome-wide linkage disequilibrium (LD) map ...,10.1038/35052563,The pattern of linkage disequilibrium (LD) acr...
4,10.1126/science.8134840,17452622,The European wild boar was crossed with the do...,10.1038/35052563,The first paper to show the use of divergent i...
...,...,...,...,...,...
35636,10.2337/db08-1168,4860455,OBJECTIVE—Regulatory T-cells (Tregs) have cata...,10.1038/s41573-019-0041-4,This article describes the good manufacturing ...
35637,10.1126/science.aar3246,4860145,Engineering cytokine-receptor pairs Interleuki...,10.1038/s41573-019-0041-4,This study reports the generation of an orthog...
35638,10.1126/science.aad2791,62290395,T cells target peptide combos One of the endur...,10.1038/s41573-019-0041-4,This article shows that some diabetogenic T ce...
35639,10.1073/pnas.1902566116,82979762,Polymorphic HLAs form the primary immune barri...,10.1038/s41573-019-0041-4,This article describes the development of gene...
35640,10.4049/jimmunol.167.3.1245,20436631,Abstract Thymectomy in mice on neonatal day 3 ...,10.1038/s41573-019-0041-4,"Together with Levings et al. (2001), Jonuleit ..."

In [4]:
dataset_df.to_csv(data_dir / "BiomedTLDR_dataset.tsv", sep="\t", index=False)